### ISSUE TITLE
Obsolete implementation of JSON-RPC Protocol

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-rs#112]
Should be align with the actual JSON RPC API version.

**Comment by dulanov** [comment]
@sorpaas and it's also up to you to change impl., jsonrpc works good, but a little bit magic, you can reimpl. directly with Hyper, for example.

**Comment by sorpaas** [comment]
@dulanov So this issue is for the Ethereum JSON-RPC, right?

**Comment by dulanov** [comment]
It's our own API, but it was inspired from `personal` geth module and from another Ethereum JSON RPC methods.

**Comment by sorpaas** [comment]
It's #108 then? Okay. `jsonrpc` is an RPC client. Definitely that needs to get changed because now we're implementing an RPC server.

I think I'll continue to use `serde_derive` with some generic functions and, as you mentioned, Hyper. Hopefully it can save some LoC.

**Comment by sorpaas** [comment]
(Thought you meant SputnikVM's `jsonrpc`... Anyway, I think Parity's `jsonrpc` magic would work fine for us now. I'll continue to use the current design.)

**Comment by dulanov** [comment]
Ok, good.

**Comment by sorpaas** [comment]
@dulanov I'm thinking about change all `IoBuilder::add_async_method` to `IoBuilder::add_method` for now. Will this work or do you have any concern in this?

We're not taking advantage of any `futures` feature -- all current calls just directly call `futures::finished` or `futures::error`. So I don't think we speed things up by using async methods. By doing this, I can also remove the macros and use `try!` and question mark syntax to handle everything.

**Comment by dulanov** [comment]
I think you are right, yes.

**Comment by sorpaas** [comment]
@dulanov Do you mind to change those RPC calls that contains more than one optional parameters to use a struct instead? For example, right now `emerald_newAccount` is `[account, passphrase, chain/chain_id]`. If we change this to `[{"account":.., "passphrase":.., "chain":..}]`, that would make everything a lot easier.

Right now, it would require to enumerate all the possibilities (even if we parse `Vec<Value>` one by one, it would require the same technique to deal with edge cases). But if those optional parameters are tagged, then there would be no way to misplace those arguments.

**Comment by dulanov** [comment]
But there is one RPC call - `emerald_signTransaction`, and it may takes up to a minute, so better to impl. as async call.
