### ISSUE TITLE
sendTransaction: invalid input length

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-rs#118]
```
TRACE:jsonrpc_core::io: Request: {"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0x7e1f623b262ff422427afc49cb4685534da91a08","password":"foo","to":"0x8f6be4eea14d192c7dc575ddf8e8ccc6b4434989","gas":"0x5208","gasPrice":"0x04a817c800","value":"0x9bd30122940485260eeee00000"}],"id":13}.
INFO:reqwest::client: Request: Post http://127.0.0.1:8545/
INFO:reqwest::response: Response: '200 OK' for http://127.0.0.1:8545/
DEBUG:jsonrpc_core::io: Response: Some("{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32602,\"message\":\"Invalid data format: Invalid input length\"},\"id\":13}").
```

**Comment by splix** [comment]
I had same issue when I was using `mainnet` by mistake. You should use `testnet` for now

**Comment by whilei** [comment]
am using a private net

**Comment by splix** [comment]
ah, I guess that's the reason. connector uses `chain_id` for testnet

**Comment by whilei** [comment]
Aha, gotcha. Will try testnet. 

To that point -- do you have any system in place for mocking transactions on the testnet? Slash can you send me a bunch of fake moola on a testnet account so I can develop with some transactions in the GUI?

**Comment by whilei** [comment]
😍 🤑 `045ee559c8232fe8a32b75b801f2a6995e460fab`

**Comment by splix** [comment]
I usually run mining, because I need that anyway to process transactions

**Comment by whilei** [comment]
It will take a long time for me to be able to mine -- my syncing still has quite a ways to go

**Comment by whilei** [comment]
I will leave it running overnight in any case

**Comment by splix** [comment]
hey, you don't need to waste your electricity on testnet, run when you use it

**Comment by whilei** [comment]
Won't I have to wait to mine until I reach max network height?

**Comment by splix** [comment]
try`--fast`, it's much faster :)
