### ISSUE TITLE
Doesn't sign transaction

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-rs#12]
Sign transaction if password is passed with transaction json. if password is invalid, respond with 403 Forbidden

Another option would be passing password as http header ("X-Emerald-Password"?)

**Comment by dulanov** [comment]
Connector should transform 'eth_sendTransaction' into 'eth_sendRawTransaction' and send it futher to client, right? For this we first need to add support for accounts keys encripted in geth compatable JSON format. Or as an alternative, we can start parity with '--unlock'. Relates to github/emerald-wallet#154.

**Comment by splix** [comment]
Yes, it should call `eth_sendRawTransaction`

**Comment by dulanov** [comment]
Good, will be done after #15.
