### ISSUE TITLE
Support any URL for RPC

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-rs#128]
Currently you have to set `host` and `port`, which may not work for public RPC endpoints (for example Gastracker). We need to support plain URL

For example https://api.gastracker.io/web3 (also notice that it's under `https`)

**Comment by sorpaas** [comment]
Emerald's RPC right now does not need to talk with an Ethereum RPC endpoint. It's used standalone and doesn't require any network communication. So I think we should be fine here?

**Comment by splix** [comment]
Ah, right. I'm just using an old version for development
