### ISSUE TITLE
Lack of support for hardware keys (trezor/ledger)

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-rs#133]

**Comment by elaineo** [comment]
Does this require a reimplementation of TrezorConnect API (currently LGPL license)? https://github.com/trezor/connect

**Comment by sjmackenzie** [comment]
LGPL isn't viral, we can use this.

**Comment by sorpaas** [comment]
A feature that I would really like to see is to allow encrypting/decrypting Ethereum private key using a GPG key rather than passphrase. This allows those who already have a hardware GPG key to have stronger security if we can ensure that we only decrypt Ethereum keys when needed.

**Comment by splix** [comment]
Isn't viral unless you include it into your code.

**Comment by sjmackenzie** [comment]
@splix please show me an example.

**Comment by splix** [comment]
@sjmackenzie https://www.gnu.org/licenses/lgpl-3.0.en.html ("_p4. Combined Works_" especially) Basically you have a choice: dynamically link LGPL library or relicense the project under GPL.

**Comment by sjmackenzie** [comment]
If you link against a shared object that is LGPL the code is *not* viral. If you start copy pasting code in then you'll be affected. As linking to shared objects is probably the most common method of including code in the C world, which means the unix world.

**Comment by sjmackenzie** [comment]
I obviously mean link to shared objects and not copy paste code in.

**Comment by sjmackenzie** [comment]
Other than the MPLv2 which has a file level boundary the only clean boundary is library level.

**Comment by sjmackenzie** [comment]
But actually this raises a good point. We cannot use LGPL rust crates for the same reason LGPL is viral for Java. See Rust src is packed into a crate.

**Comment by r8d8** [comment]
Ledger support added for first iteration.
