### ISSUE TITLE
Inconsistent `--chain-id` and `--chain` arguments

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-rs#157]
- Should `--chain` name be required with `--chain-id`?
- 'testnet' should be renamed 'morden'

```
  -c, --chain <mainnet|testnet>             Chain name [default: mainnet]
      --chain-id <id>                       Chain id number [default: 61]
```
```
~/Library/Application Support/Emerald Wallet/bin  ⟠ ./emerald server --verbose 1 --chain-id 62
[INFO]	Starting Emerald Connector - v0.1.0
[ERROR]	Inconsistent `--chain-id` and `--chain` arguments!

~/Library/Application Support/Emerald Wallet/bin  ⟠ ./emerald server --verbose 1 --chain-id 62 --chain testnet
[INFO]	Starting Emerald Connector - v0.1.0
[INFO]	security level set to 'normal'
[INFO]	Connector started on http://127.0.0.1:1920
^C
```

**Comment by dulanov** [comment]
`server` should take `chain` or `chain-id` as default for futher JSON-RPC requests. `chain` has higher priority in relation to `chain-id`. `testnet` is more clearer name for me than `morden`.

**Comment by dulanov** [comment]
@whilei you should spawn `emerald server` and select required chain directly in JSON-RPC. I wasn't planning on restarting for each selectde network, they should work in parallel.

**Comment by whilei** [comment]
Ok, so similar keystore storage pattern to geth. 

@dulanov There are multiple testnets (ropsten, kovan, rinkeby...), I think it is more descriptive and extensible to use network by name, which would work similarly to geth; see https://github.com/ethereumproject/go-ethereum/pull/224.

**Comment by dulanov** [comment]
I don't think so, `emerald-rs` isnt's a client like geth, it's just a purse, important only the purpose of selected network. For all of `ropsten, kovan, rinkeby` user should prefer similar test accounts.

**Comment by whilei** [comment]
What is the RPC call for selecting a chain?

**Comment by dulanov** [comment]
The problem is only with replay protection, because `ropsten, kovan, rinkeby` use different `chain-id`, hm.

**Comment by dulanov** [comment]
Every JSON-RPC has additional option object with selected chain info - https://github.com/ethereumproject/emerald-rs/blob/master/docs/api.adoc#emerald_signtransaction.

**Comment by dulanov** [comment]
@whilei you don't need to switch chain explicitly, just use additional optional object.

**Comment by whilei** [comment]
Ooooh... gotcha. Will need in this case to update the wallet's calls (it was using the cli to set `chain` and `chainId`).

**Comment by dulanov** [comment]
Yes, my idea was to transfer the required chain via JSON-RPC.
