### ISSUE TITLE
Problem: by default `server` and `cli` subcommands have same verbosity level

### ISSUE THREAD

**Issue by sjmackenzie** [ethereumproject/emerald-rs#163]
Solution: we should fail with error messages and silently succeed when in CLI mode, but when in `server` so it's standard to run INFO  when in `server` mode.

**Comment by dulanov** [comment]
But now we don't have CLI mode, or?

**Comment by dulanov** [comment]
No, first of all, it's not good to make same logic different between subcommands, second, we redesigned it with @r8d8, not by default verbosity is disabled:

```
-q, quiet
-v, verbosity (trace level, like `--verbose 7` for geth)
```

And by default it's something between, similar to geth - `errors`, `warnings`, `info`.

**Comment by sjmackenzie** [comment]
It's standard practice for CLI programs to exit with exit code 0 and not print anything to `stdout`. If there is an error you'll exit the program with an error code other than 0 and print information to `stderr`. But as  the `emerald server` *is* a logical difference from the standard cli and it's customary to run a server with INFO level logging so there will be a difference. Otherwise just default `emerald server` to the same level as the standard verbosity of a CLI program.

**Comment by dulanov** [comment]
We want to start with very simple scheme, without verbosity levels at all. As simple as possible, like hammer      or Russian harmonica.

**Comment by dulanov** [comment]
And for `server` subcommand we should apply standart CLI rules, geth way not for us.
