### ISSUE TITLE
Performance bottleneck for `Keyfiles` operations

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/emerald-rs#169]
Emerald uses fs system for all Keyfile operatons. It will be bottleneck when it will be used for scripting. Need to use some in-memory db (rocksdb, leveldb, etc.)

**Comment by dulanov** [comment]
Why it's bottleneck, you can open files without locking and read them in parallel?

**Comment by dulanov** [comment]
In java, for exmple: `try (InputStream is = Files.newInputStream(path, StandardOpenOption.READ)) ...`.

**Comment by splix** [comment]
@dulanov is there any index for address/uuid? for Geth the bottleneck that you have to open every file (even in parallel) just to find required one. It become a bottleneck when you have hundreds of thousands keyfiles to check

**Comment by dulanov** [comment]
@splix not yet, what you decided to use in Geth for that?

**Comment by splix** [comment]
kv database

**Comment by r8d8** [comment]
Actually Keyfile have his UUID included into filename, but it's not mandatory and you can't rely on this.
Geth uses address in keyfile's filename

**Comment by splix** [comment]
Even if you'll use address in filename
1. it's still takes time to read list of files and scan to find proper file to read. not really a index
2. you can't guarantee user will never edit filename or copy new keys from geth/parity/backup. because if you keep the as plain files it's expected you can do that

**Comment by dulanov** [comment]
Ok, between LevelDB and RocksDB I prefer LevelDB, because more simple and stable.

**Comment by dulanov** [comment]
But after quick review I found that rocksdb has better support for Rust.
