### ISSUE TITLE
Errors are spreaded between different mods

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/emerald-rs#179]
We have many errors mod right now. This sometimes creates problem for implementing `From` and `Into` trait to convert between each other. Implementing those traits are essential to Rust's `try!` macro and ? syntax.

Many projects, like [hyper](https://github.com/hyperium/hyper/blob/master/src/error.rs) (and SputnikVM!) also uses a single error mod design.

**Comment by r8d8** [comment]
It is good practice to separate errors stuff from your logic.
In either case it will be mess.
All `From` and `Into`, and other stuff for errors, stays localized in one mode - gets easier to manage, than crawling in files messed with logic.
