### ISSUE TITLE
`emerald_listAccounts` JSON-RPC call doesn't return account description

### ISSUE THREAD

**Issue by gagarin55** [ethereumproject/emerald-rs#184]
As `emerald_updateAccount` can change account's _description_ `emerald_listAccounts` RPC method should return account's _description_. 

This functionality used in emerald wallet.

**Comment by dulanov** [comment]
Yes, make sense, we should instead of success flag return whole account.

**Comment by dulanov** [comment]
Ah, I don't understand correctly, that true, `emerald_listAccounts` should return `description` if there is one. It's just bug.
