### ISSUE TITLE
Sign the transaction with network id

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/emerald-rs#220]
https://github.com/ethereumproject/emerald-rs/blob/69189b992454eebe6f53945700cdfb938b85a0ef/emerald-core/src/core/signature.rs#L116

According to EIP155, 27 is the valid transaction signature without network id. With network id I it's 35 + 2 * network_id. So I think this line should be:

```
buf[0] = (rid.to_i32() + if let Some(n) = self.network_id { 35 + n * 2 } else { 27 }) as u8;
```

**Comment by r8d8** [comment]
https://github.com/ethereumproject/emerald-rs/blob/69189b992454eebe6f53945700cdfb938b85a0ef/emerald-core/src/core/transaction.rs#L42
It is already here, 
will refactor this stuff after db storage
