### ISSUE TITLE
[RPC] updateAccount - is description really optional?

### ISSUE THREAD

**Issue by gagarin55** [ethereumproject/emerald-rs#224]
As it said in documentation (https://github.com/ethereumproject/emerald-rs/blob/master/docs/api.adoc)

`description` argument is optional in `updateAccount` method.

Is it https://github.com/ethereumproject/emerald-rs/blob/master/emerald-core/src/rpc/serves.rs#L223 ?

**Comment by r8d8** [comment]
Yeap,  it's optional
