### ISSUE TITLE
Need to be able to run trace call

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/emerald-rs#30]
For the wallet to estimate gas needed for contract interactions, the connector needs an interface for `trace_call`

eg:
`{"method": "trace_call", "params": [objCall, ["stateDiff", "trace", "vmTrace"]]}`

**Comment by dulanov** [comment]
This method call works only with parity, not wih geth.

**Comment by dulanov** [comment]
@splix do we need to add support also for the geth and do you know how it can be done?

**Comment by splix** [comment]
Geth has undocumented `eth_traceCall` method, which returns amount of gas for a tx

**Comment by dulanov** [comment]
With similar parameters, we should support it too?

**Comment by splix** [comment]
I think we should support Geth's standard, and make this method official. It's actually simpler than parity's trace.

For geth it's:
`eth_traceCall` with parameters:

- `Object` - The transaction call object (from/to/gas/gasPrice/value/data)
- `QUANTITY|TAG` - integer block number, or the string "latest", "earliest" or "pending"

returns:
```
{
	"jsonrpc": "2.0",
	"id": 1,
	"result": {
		"gas": 22680,
		"returnValue": ""
	}
}
```

**Comment by dulanov** [comment]
Will be done after #14.
