### ISSUE TITLE
User unable to save account names

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/emerald-rs#31]
When creating an account or importing a wallet, the user has the option to enter an account name, since they may not be able to remember `0x35deeeeaambwmb` or whatever. 

Can the connector support this?

currently, interface looks like `rpc("personal_newAccount", [password])`

**Comment by splix** [comment]
Account name and description would be useful. I guess we can pass an object instead of password, like:
```
{"password": "****", "name": "My Account", "description": "Personal stuff"}
```
and store these values in account meta

**Comment by r8d8** [comment]
How about optional parameters, or they all will be mandatory?

**Comment by elaineo** [comment]
@r8d8 I believe only pw is necessary. Client can use accountId if there is no name.

**Comment by r8d8** [comment]
![screenshot_2017-05-22_12-55-09](https://cloud.githubusercontent.com/assets/8018746/26318230/8e456f14-3f2b-11e7-9670-761f0088f75d.png)

Should there also exist `description` field?

**Comment by elaineo** [comment]
Yeah, I think `description` should be included, but optional.
