### ISSUE TITLE
Client should be able to load account transactions

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/emerald-rs#98]
Client wallet needs to load transactions by account. There are a few ways to do it:

- [`eth_filter`](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter): filter transactions by block. this is slow, and does not catch internal transactions
- [`trace_filter`](https://github.com/paritytech/parity/wiki/JSONRPC-trace-module#trace_filter): also slow, but it gets internal transactions. Also, this is currently only implemented in parity
- Store transactions locally

Which option?

**Comment by dulanov** [comment]
https://ethereum.stackexchange.com/questions/2531/common-useful-javascript-snippets-for-geth/3478#3478

**Comment by dulanov** [comment]
Filter is more about smart contract events, it looks like web3 hasn't friendly way to receive last transactions by address.

**Comment by elaineo** [comment]
@dulanov is that the best way to do it then? have the wallet fetch block-by-block and search for address transactions? that still misses internal TX.

**Comment by dulanov** [comment]
https://github.com/ethereum/go-ethereum/issues/1749

**Comment by dulanov** [comment]
@elaineo why you need internal transactions, is it not just internal calls between smart contracts?

**Comment by dulanov** [comment]
I don't find yet the best way @elaineo, I am trying to collect the puzzle.

**Comment by dulanov** [comment]
I think we need to discuss it, because normally it require something like [Instrumenting EVM](https://ethereum.stackexchange.com/questions/4446/instrumenting-evm).

**Comment by elaineo** [comment]
@dulanov If internal calls between smart contracts change the balance, then that should look like a transaction in the account. Parity's [`trace_filter`](https://github.com/paritytech/parity/wiki/JSONRPC-trace-module#trace_filter) traces internal transactions, but it's slow. Etherhub (and i think gastracker? @splix ) run the trace and store the transactions in an internal db to reduce fetch time, but i don't know if we want to store so much in the connector.

**Comment by dulanov** [comment]
Smart contract balance, we speak about tokens, not about accounts? Connector can't store all of them, because you can send transaction somewhere also and the connector lose that. We main problem with this task, it's not normally wallet function, but for tools like etherscan and gastracker. In stackoverflow advise to use their API.

**Comment by elaineo** [comment]
@dulanov oh, gastracker has API for account history? i didn't know that :)
okay, so for the recent transaction issue (https://github.com/ethereumproject/emerald-wallet/issues/11) we will just grab recent blocks and filter out transactions on the client wallet side. There is no need to load account transactions through the connector then.

**Comment by dulanov** [comment]
I like anouther one, just a link to gastracker, what do you think about all these @splix ?

**Comment by dulanov** [comment]
There is another problem:

```
A fast synced client does not have historical data about past transactions that were received by an account, only the logs, so if a client fast syncs, it cannot ever figure out what happened in the past with plain accounts.
```

So, you should force users to do full sync, @splix, that's right?

**Comment by splix** [comment]
Yes, there is no standard way to get tx history, especially for internal calls. But we can get that from 3rd party, such as gastracker.io or etherhub.io. It should be configurable though, let's give user an option which explorer to use, and allow to disable it at all, if he concerns about privacy

**Comment by r8d8** [comment]
So, this functionality can be done from wallet only, or connector need to provide some?

**Comment by splix** [comment]
from wallet only
